### ISSUE TITLE
Error on connecting to local VNC

### ISSUE THREAD

**Issue by khoaakt** [os-js/osjs-vnc-application#8] opened 2020-06-20 20:45 UTC
I cannot connect to my local VNC Server (lastest noVNC installed).

**Screenshot:**
![image](https://user-images.githubusercontent.com/6000592/85211244-67100180-b371-11ea-94d6-361814031dc9.png)

**Comment by andersevenrud** [comment] 2020-06-20 21:09
A bit strange seeing that if going by the code this should not be an issue.

But I'll look into it :)

**Comment by andersevenrud** [comment] 2020-06-20 21:19
I just released a new version that might solve this issue for you. Still not 100% sure what's going on, but it's related Babel transpilation.

**Comment by andersevenrud** [comment] 2020-06-20 23:37
I'm going to close this prematurely because it seems to have fixed things on my end at least. I cannot reproduce this anymore. But if you do, please re-open this :)

**Closed by andersevenrud** 2020-06-20 23:37 UTC
Labels: bug
